name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          architecture: x64
          java-version: 1.8
      - name: Build with Maven
        run: mvn package --batch-mode
